var searchData=
[
  ['of_20a_20reporter_0',['Other expected functionality of a reporter',['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md586',1,'']]],
  ['of_20args_20and_20config_1',['Let Catch2 take full control of args and config',['../md_build_2__deps_2catch2-src_2docs_2own-main.html#autotoc_md259',1,'']]],
  ['of_20benchmark_20samples_20to_20collect_2',['Specify the number of benchmark samples to collect',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md76',1,'']]],
  ['of_20catch2_3',['Commercial users of Catch2',['../md_build_2__deps_2catch2-src_2docs_2commercial-users.html#autotoc_md90',1,'']]],
  ['of_20collected_20benchmark_20samples_4',['Disable statistical analysis of collected benchmark samples',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md79',1,'']]],
  ['of_20conduct_5',['Contributor Covenant Code of Conduct',['../md_build_2__deps_2catch2-src_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'']]],
  ['of_20examples_6',['of examples',['../md_build_2__deps_2catch2-src_2docs_2list-of-examples.html#autotoc_md179',1,'List of examples'],['../md_build_2__deps_2catch2-src_2docs_2list-of-examples.html',1,'list-of-examples']]],
  ['of_20failures_7',['Aborting after a certain number of failures',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md59',1,'']]],
  ['of_20functions_20from_20c_20s_20stdlib_8',['Unqualified usage of functions from C&apos;s stdlib',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md133',1,'']]],
  ['of_20resamples_20for_20bootstrapping_9',['Specify the number of resamples for bootstrapping',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md77',1,'']]],
  ['of_20three_20implementacija_10',['Rule of Three Implementacija',['../md__r_e_a_d_m_e.html#autotoc_md689',1,'']]],
  ['of_20time_20in_20milliseconds_20spent_20on_20warming_20up_20each_20test_11',['Specify the amount of time in milliseconds spent on warming up each test',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md80',1,'']]],
  ['of_20variables_20or_20expressions_12',['Quickly capture value of variables or expressions',['../md_build_2__deps_2catch2-src_2docs_2logging.html#autotoc_md186',1,'']]],
  ['oji_20užduotis_13',['oji užduotis',['../md__r_e_a_d_m_e.html',1,'1-oji užduotis'],['../md__r_e_a_d_m_e.html#autotoc_md681',1,'2-oji užduotis']]],
  ['old_20style_14',['Writing custom matchers (old style)',['../md_build_2__deps_2catch2-src_2docs_2matchers.html#autotoc_md198',1,'']]],
  ['older_20versions_15',['Older versions',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md557',1,'Even Older versions'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md490',1,'Older versions']]],
  ['on_16',['Tooling integration (CI, test runners and so on)',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md22',1,'']]],
  ['on_20github_17',['Release on GitHub',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md565',1,'']]],
  ['on_20using_20catch2_18',['Best practices and other tips on using Catch2',['../md_build_2__deps_2catch2-src_2docs_2usage-tips.html#autotoc_md644',1,'']]],
  ['on_20warming_20up_20each_20test_19',['Specify the amount of time in milliseconds spent on warming up each test',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md80',1,'']]],
  ['only_20if_20tests_20will_20be_20run_20',['How do I run global setup/teardown only if tests will be run?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md149',1,'']]],
  ['open_20source_20projects_20using_20catch2_21',['Open Source projects using Catch2',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md206',1,'']]],
  ['openalpp_22',['&lt;a href=&quot;https://github.com/Laguna1989/OpenALpp&quot;&gt;OpenALpp&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md230',1,'']]],
  ['opensource_20users_23',['opensource-users',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html',1,'']]],
  ['operator_24',['operator',['../md__r_e_a_d_m_e.html#autotoc_md694',1,'Įvesties Operatorius (operator&amp;gt;&amp;gt;)'],['../md__r_e_a_d_m_e.html#autotoc_md695',1,'Išvesties Operatorius (operator&amp;lt;&amp;lt;)'],['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md178',1,'Visual Studio 2022 &amp;ndash; can&apos;t compile assertion with the spaceship operator']]],
  ['operator_20overload_20for_20std_3a_3aostream_25',['operator &amp;lt;&amp;lt; overload for std::ostream',['../md_build_2__deps_2catch2-src_2docs_2tostring.html#autotoc_md628',1,'']]],
  ['operatoriai_26',['Įvesties/Išvesties Operatoriai',['../md__r_e_a_d_m_e.html#autotoc_md693',1,'']]],
  ['operatorius_27',['Kopijavimo Priskyrimo Operatorius',['../md__r_e_a_d_m_e.html#autotoc_md691',1,'']]],
  ['operatorius_20operator_28',['Operatorius operator',['../md__r_e_a_d_m_e.html#autotoc_md694',1,'Įvesties Operatorius (operator&amp;gt;&amp;gt;)'],['../md__r_e_a_d_m_e.html#autotoc_md695',1,'Išvesties Operatorius (operator&amp;lt;&amp;lt;)']]],
  ['operators_20and_20lifetimes_29',['Combining operators and lifetimes',['../md_build_2__deps_2catch2-src_2docs_2matchers.html#autotoc_md190',1,'']]],
  ['optimizer_30',['The optimizer',['../md_build_2__deps_2catch2-src_2docs_2benchmarks.html#autotoc_md21',1,'']]],
  ['option_31',['Adding new &lt;span class=&quot;tt&quot;&gt;CATCH_CONFIG&lt;/span&gt; option',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md136',1,'']]],
  ['options_32',['options',['../md_build_2__deps_2catch2-src_2docs_2own-main.html#autotoc_md261',1,'Adding your own command line options'],['../md_build_2__deps_2catch2-src_2docs_2cmake-integration.html#autotoc_md47',1,'CMake project options']]],
  ['options_20in_20cmake_33',['&lt;span class=&quot;tt&quot;&gt;CATCH_CONFIG_*&lt;/span&gt; customization options in CMake',['../md_build_2__deps_2catch2-src_2docs_2cmake-integration.html#autotoc_md48',1,'']]],
  ['or_20expressions_34',['Quickly capture value of variables or expressions',['../md_build_2__deps_2catch2-src_2docs_2logging.html#autotoc_md186',1,'']]],
  ['or_20reporters_35',['Listing available tests, tags or reporters',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md60',1,'']]],
  ['order_20test_20cases_20are_20run_36',['Specify the order test cases are run',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md68',1,'']]],
  ['organizing_20tests_20into_20binaries_37',['Organizing tests into binaries',['../md_build_2__deps_2catch2-src_2docs_2usage-tips.html#autotoc_md647',1,'']]],
  ['other_38',['Other',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md520',1,'Other'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md537',1,'Other']]],
  ['other_20changes_39',['Other changes',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md346',1,'Other changes'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md475',1,'Other changes'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md479',1,'Other changes'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md484',1,'Other changes']]],
  ['other_20core_20features_40',['Other core features',['../md_build_2__deps_2catch2-src_2docs_2why-catch.html#autotoc_md651',1,'']]],
  ['other_20expected_20functionality_20of_20a_20reporter_41',['Other expected functionality of a reporter',['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md586',1,'']]],
  ['other_20limitations_42',['Other limitations',['../md_build_2__deps_2catch2-src_2docs_2assertions.html#autotoc_md9',1,'']]],
  ['other_20macros_43',['Other macros',['../md_build_2__deps_2catch2-src_2docs_2other-macros.html#autotoc_md255',1,'']]],
  ['other_20macros_44',['other-macros',['../md_build_2__deps_2catch2-src_2docs_2other-macros.html',1,'']]],
  ['other_20notes_45',['Other notes',['../md_build_2__deps_2catch2-src_2docs_2migrate-v2-to-v3.html#autotoc_md203',1,'']]],
  ['other_20notes_3a_46',['Other notes:',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md526',1,'Other notes:'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md531',1,'Other notes:']]],
  ['other_20tips_20on_20using_20catch2_47',['Best practices and other tips on using Catch2',['../md_build_2__deps_2catch2-src_2docs_2usage-tips.html#autotoc_md644',1,'']]],
  ['other_20toggles_48',['Other toggles',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md110',1,'']]],
  ['other_3a_49',['Other:',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md546',1,'Other:'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md551',1,'Other:'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md556',1,'Other:']]],
  ['others_50',['Others',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md466',1,'']]],
  ['our_20pledge_51',['Our Pledge',['../md_build_2__deps_2catch2-src_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md1',1,'']]],
  ['our_20responsibilities_52',['Our Responsibilities',['../md_build_2__deps_2catch2-src_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md3',1,'']]],
  ['our_20standards_53',['Our Standards',['../md_build_2__deps_2catch2-src_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md2',1,'']]],
  ['out_20for_54',['Code constructs to watch out for',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md130',1,'']]],
  ['output_20colouring_55',['Override output colouring',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md84',1,'']]],
  ['output_20to_20a_20file_56',['Sending output to a file',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md61',1,'']]],
  ['output_20verbosity_57',['Output verbosity',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md87',1,'']]],
  ['overhead_58',['Performance overhead',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md625',1,'']]],
  ['overload_20for_20std_3a_3aostream_59',['operator &amp;lt;&amp;lt; overload for std::ostream',['../md_build_2__deps_2catch2-src_2docs_2tostring.html#autotoc_md628',1,'']]],
  ['override_20output_20colouring_60',['Override output colouring',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md84',1,'']]],
  ['overriding_20catch_20s_20debug_20break_20b_61',['Overriding Catch&apos;s debug break (&lt;span class=&quot;tt&quot;&gt;-b&lt;/span&gt;)',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md117',1,'']]],
  ['own_20command_20line_20options_62',['Adding your own command line options',['../md_build_2__deps_2catch2-src_2docs_2own-main.html#autotoc_md261',1,'']]],
  ['own_20main_63',['own-main',['../md_build_2__deps_2catch2-src_2docs_2own-main.html',1,'']]],
  ['own_20reporter_64',['Writing your own reporter',['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md582',1,'']]]
];
