var searchData=
[
  ['naked_20exceptions_20and_20exceptions_20related_20function_0',['Naked exceptions and exceptions-related function',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md131',1,'']]],
  ['names_20to_20run_20from_20a_20file_1',['Load test names to run from a file',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md67',1,'']]],
  ['naming_20a_20test_20run_2',['Naming a test run',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md62',1,'']]],
  ['nanodbc_3',['&lt;a href=&quot;https://github.com/lexicalunit/nanodbc/&quot;&gt;nanodbc&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md228',1,'']]],
  ['natural_20expressions_4',['Natural Expressions',['../md_build_2__deps_2catch2-src_2docs_2assertions.html#autotoc_md8',1,'']]],
  ['naudojimosi_20instrukcija_5',['Naudojimosi instrukcija',['../md__r_e_a_d_m_e.html#autotoc_md680',1,'']]],
  ['ndash_20can_20t_20compile_20assertion_20with_20the_20spaceship_20operator_6',['Visual Studio 2022 &amp;ndash; can&apos;t compile assertion with the spaceship operator',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md178',1,'']]],
  ['ndash_20raw_20string_20literal_20in_20assert_20fails_20to_20compile_7',['Visual Studio 2017 &amp;ndash; raw string literal in assert fails to compile',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md176',1,'']]],
  ['ndash_20skipping_20leaf_20sections_20after_20an_20exception_8',['Clang/G++ &amp;ndash; skipping leaf sections after an exception',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md177',1,'']]],
  ['necessary_20steps_9',['Necessary steps',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md560',1,'']]],
  ['need_20yet_20another_20c_20test_20framework_10',['Why do we need yet another C++ test framework?',['../md_build_2__deps_2catch2-src_2docs_2why-catch.html#autotoc_md649',1,'']]],
  ['nested_20in_20loops_11',['Sections nested in loops',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md169',1,'']]],
  ['new_20catch_5fconfig_20option_12',['Adding new &lt;span class=&quot;tt&quot;&gt;CATCH_CONFIG&lt;/span&gt; option',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md136',1,'']]],
  ['new_20features_13',['New features',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md483',1,'']]],
  ['new_20features_20minor_20changes_14',['New features/ minor changes',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md535',1,'']]],
  ['new_20source_20file_20template_15',['New source file template',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md135',1,'']]],
  ['new_20style_16',['Writing custom matchers (new style)',['../md_build_2__deps_2catch2-src_2docs_2matchers.html#autotoc_md199',1,'']]],
  ['newsbeuter_17',['&lt;a href=&quot;https://github.com/akrennmair/newsbeuter&quot;&gt;Newsbeuter&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md249',1,'']]],
  ['next_20steps_18',['Next steps',['../md_build_2__deps_2catch2-src_2docs_2tutorial.html#autotoc_md642',1,'']]],
  ['non_20const_20function_20for_20test_5fcase_5fmethod_19',['Non-const function for &lt;span class=&quot;tt&quot;&gt;TEST_CASE_METHOD&lt;/span&gt;',['../md_build_2__deps_2catch2-src_2docs_2deprecations.html#autotoc_md144',1,'']]],
  ['non_20templated_20test_20fixtures_20',['Non-Templated test fixtures',['../md_build_2__deps_2catch2-src_2docs_2test-fixtures.html#autotoc_md605',1,'']]],
  ['nonius_21',['&lt;a href=&quot;https://github.com/libnonius/nonius&quot;&gt;Nonius&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md229',1,'']]],
  ['notes_22',['notes',['../md_build_2__deps_2catch2-src_2docs_2migrate-v2-to-v3.html#autotoc_md203',1,'Other notes'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md265',1,'Release notes'],['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md563',1,'Release notes'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html',1,'release-notes']]],
  ['notes_3a_23',['notes:',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md526',1,'Other notes:'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md531',1,'Other notes:']]],
  ['number_24',['Incrementing version number',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md562',1,'']]],
  ['number_20generator_25',['Specify a seed for the Random Number Generator',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md72',1,'']]],
  ['number_20generators_3a_20details_26',['Random number generators: details',['../md_build_2__deps_2catch2-src_2docs_2generators.html#autotoc_md162',1,'']]],
  ['number_20of_20benchmark_20samples_20to_20collect_27',['Specify the number of benchmark samples to collect',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md76',1,'']]],
  ['number_20of_20failures_28',['Aborting after a certain number of failures',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md59',1,'']]],
  ['number_20of_20resamples_20for_20bootstrapping_29',['Specify the number of resamples for bootstrapping',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md77',1,'']]],
  ['numbers_30',['comparing-floating-point-numbers',['../md_build_2__deps_2catch2-src_2docs_2comparing-floating-point-numbers.html',1,'']]],
  ['numbers_20with_20catch2_31',['Comparing floating point numbers with Catch2',['../md_build_2__deps_2catch2-src_2docs_2comparing-floating-point-numbers.html#autotoc_md92',1,'']]]
];
