var searchData=
[
  ['last_20section_20fails_0',['Tests might be run again if last section fails',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md170',1,'']]],
  ['lcov_1',['CodeCoverage module (GCOV, LCOV...)',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md32',1,'']]],
  ['leaf_20sections_20after_20an_20exception_2',['Clang/G++ &amp;ndash; skipping leaf sections after an exception',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md177',1,'']]],
  ['let_20catch2_20take_20full_20control_20of_20args_20and_20config_3',['Let Catch2 take full control of args and config',['../md_build_2__deps_2catch2-src_2docs_2own-main.html#autotoc_md259',1,'']]],
  ['level_20tools_4',['Low-level tools',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md31',1,'']]],
  ['lex_5',['lex',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md70',1,'']]],
  ['libcluon_6',['&lt;a href=&quot;https://github.com/chrberger/libcluon&quot;&gt;libcluon&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md226',1,'']]],
  ['libidentify_20standard_7',['Identify framework and version according to the libIdentify standard',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md73',1,'']]],
  ['libraries_20frameworks_8',['Libraries &amp;amp; Frameworks',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md207',1,'']]],
  ['library_9',['Can I compile Catch2 into a dynamic library?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md155',1,'']]],
  ['lifetimes_10',['Combining operators and lifetimes',['../md_build_2__deps_2catch2-src_2docs_2matchers.html#autotoc_md190',1,'']]],
  ['like_20message_20macros_20and_20spawned_20threads_11',['Assertion-like message macros and spawned threads',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md615',1,'']]],
  ['limitations_12',['limitations',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md167',1,'Known limitations'],['../md_build_2__deps_2catch2-src_2docs_2limitations.html',1,'limitations'],['../md_build_2__deps_2catch2-src_2docs_2assertions.html#autotoc_md9',1,'Other limitations']]],
  ['limits_13',['Implementation limits',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md168',1,'']]],
  ['line_14',['line',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md53',1,'Command line'],['../md_build_2__deps_2catch2-src_2docs_2command-line.html',1,'command-line']]],
  ['line_20options_15',['Adding your own command line options',['../md_build_2__deps_2catch2-src_2docs_2own-main.html#autotoc_md261',1,'']]],
  ['linking_20is_20extremely_20slow_16',['MinGW/CygWin compilation (linking) is extremely slow',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md171',1,'']]],
  ['list_20of_20examples_17',['List of examples',['../md_build_2__deps_2catch2-src_2docs_2list-of-examples.html#autotoc_md179',1,'']]],
  ['list_20of_20examples_18',['list-of-examples',['../md_build_2__deps_2catch2-src_2docs_2list-of-examples.html',1,'']]],
  ['listeners_19',['Event Listeners',['../md_build_2__deps_2catch2-src_2docs_2event-listeners.html#autotoc_md146',1,'']]],
  ['listeners_20',['event-listeners',['../md_build_2__deps_2catch2-src_2docs_2event-listeners.html',1,'']]],
  ['listing_20available_20tests_20tags_20or_20reporters_21',['Listing available tests, tags or reporters',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md60',1,'']]],
  ['listings_20events_22',['Listings events',['../md_build_2__deps_2catch2-src_2docs_2reporter-events.html#autotoc_md576',1,'']]],
  ['lists_23',['Template fixtures with types specified in template type lists',['../md_build_2__deps_2catch2-src_2docs_2test-fixtures.html#autotoc_md611',1,'']]],
  ['lite_20core_24',['&lt;a href=&quot;https://github.com/couchbase/couchbase-lite-core&quot;&gt;Couchbase-lite-core&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md217',1,'']]],
  ['literal_20in_20assert_20fails_20to_20compile_25',['Visual Studio 2017 &amp;ndash; raw string literal in assert fails to compile',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md176',1,'']]],
  ['literals_20udl_20for_20catch2_20types_26',['User-Defined Literals (UDL) for Catch2&apos; types',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md134',1,'']]],
  ['llama_27',['&lt;a href=&quot;https://github.com/alpaka-group/llama&quot;&gt;LLAMA&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md225',1,'']]],
  ['lldb_20scripts_28',['gdb and lldb scripts',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md34',1,'']]],
  ['load_20test_20names_20to_20run_20from_20a_20file_29',['Load test names to run from a file',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md67',1,'']]],
  ['local_20scope_30',['Logging without local scope',['../md_build_2__deps_2catch2-src_2docs_2logging.html#autotoc_md184',1,'']]],
  ['logging_31',['logging',['../md_build_2__deps_2catch2-src_2docs_2logging.html',1,'']]],
  ['logging_20macros_32',['Logging macros',['../md_build_2__deps_2catch2-src_2docs_2logging.html#autotoc_md183',1,'']]],
  ['logging_20without_20local_20scope_33',['Logging without local scope',['../md_build_2__deps_2catch2-src_2docs_2logging.html#autotoc_md184',1,'']]],
  ['loop_20machine_34',['&lt;a href=&quot;https://github.com/monocasual/giada&quot;&gt;Giada - Your Hardcore Loop Machine&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md247',1,'']]],
  ['loops_35',['Sections nested in loops',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md169',1,'']]],
  ['low_20level_20tools_36',['Low-level tools',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md31',1,'']]]
];
