var searchData=
[
  ['a_20certain_20number_20of_20failures_0',['Aborting after a certain number of failures',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md59',1,'']]],
  ['a_20dynamic_20library_1',['Can I compile Catch2 into a dynamic library?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md155',1,'']]],
  ['a_20file_2',['a file',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md67',1,'Load test names to run from a file'],['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md61',1,'Sending output to a file']]],
  ['a_20reporter_3',['Other expected functionality of a reporter',['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md586',1,'']]],
  ['a_20reporter_20to_20use_4',['Choosing a reporter to use',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md56',1,'']]],
  ['a_20seed_20for_20the_20random_20number_20generator_5',['Specify a seed for the Random Number Generator',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md72',1,'']]],
  ['a_20tag_6',['Signing a tag',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md566',1,'']]],
  ['a_20test_7',['Process isolation in a test',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md173',1,'']]],
  ['a_20test_20run_8',['Naming a test run',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md62',1,'']]],
  ['a_20vulnerability_9',['Reporting a Vulnerability',['../md_build_2__deps_2catch2-src_2_s_e_c_u_r_i_t_y.html#autotoc_md664',1,'']]],
  ['abi_20stability_20policy_10',['What is Catch2&apos;s ABI stability policy?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md152',1,'']]],
  ['aborting_20after_20a_20certain_20number_20of_20failures_11',['Aborting after a certain number of failures',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md59',1,'']]],
  ['accessorpp_12',['&lt;a href=&quot;https://github.com/wqking/accessorpp&quot;&gt;accessorpp&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md208',1,'']]],
  ['according_20to_20the_20libidentify_20standard_13',['Identify framework and version according to the libIdentify standard',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md73',1,'']]],
  ['across_20threads_14',['INFO across threads',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md620',1,'']]],
  ['adding_20new_20catch_5fconfig_20option_15',['Adding new &lt;span class=&quot;tt&quot;&gt;CATCH_CONFIG&lt;/span&gt; option',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md136',1,'']]],
  ['adding_20your_20own_20command_20line_20options_16',['Adding your own command line options',['../md_build_2__deps_2catch2-src_2docs_2own-main.html#autotoc_md261',1,'']]],
  ['advanced_20benchmarking_17',['Advanced benchmarking',['../md_build_2__deps_2catch2-src_2docs_2benchmarks.html#autotoc_md19',1,'']]],
  ['after_20a_20certain_20number_20of_20failures_18',['Aborting after a certain number of failures',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md59',1,'']]],
  ['after_20an_20exception_19',['Clang/G++ &amp;ndash; skipping leaf sections after an exception',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md177',1,'']]],
  ['again_20if_20last_20section_20fails_20',['Tests might be run again if last section fails',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md170',1,'']]],
  ['against_20silent_20early_20termination_21',['Create file to guard against silent early termination',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md88',1,'']]],
  ['ahead_22',['&lt;a href=&quot;https://github.com/CleverRaven/Cataclysm-DDA&quot;&gt;Cataclysm: Dark Days Ahead&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md213',1,'']]],
  ['aliases_23',['Tag aliases',['../md_build_2__deps_2catch2-src_2docs_2test-cases-and-sections.html#autotoc_md597',1,'']]],
  ['all_20benchmarks_24',['Skip all benchmarks',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md75',1,'']]],
  ['allow_20running_20the_20binary_20without_20tests_25',['Allow running the binary without tests',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md86',1,'']]],
  ['alpaka_26',['&lt;a href=&quot;https://github.com/alpaka-group/alpaka&quot;&gt;alpaka&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md209',1,'']]],
  ['already_20available_27',['Already available',['../md_build_2__deps_2catch2-src_2docs_2list-of-examples.html#autotoc_md180',1,'']]],
  ['amalgamated_20files_28',['Signing the amalgamated files',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md567',1,'']]],
  ['amending_20the_20catch2_20config_29',['Amending the Catch2 config',['../md_build_2__deps_2catch2-src_2docs_2own-main.html#autotoc_md260',1,'']]],
  ['amount_20of_20time_20in_20milliseconds_20spent_20on_20warming_20up_20each_20test_30',['Specify the amount of time in milliseconds spent on warming up each test',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md80',1,'']]],
  ['an_20exception_31',['Clang/G++ &amp;ndash; skipping leaf sections after an exception',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md177',1,'']]],
  ['analysis_20of_20collected_20benchmark_20samples_32',['Disable statistical analysis of collected benchmark samples',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md79',1,'']]],
  ['analysis_20support_33',['Static analysis support',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md118',1,'']]],
  ['and_20catchaddtests_20cmake_34',['&lt;span class=&quot;tt&quot;&gt;Catch.cmake&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;CatchAddTests.cmake&lt;/span&gt;',['../md_build_2__deps_2catch2-src_2docs_2cmake-integration.html#autotoc_md40',1,'']]],
  ['and_20config_35',['Let Catch2 take full control of args and config',['../md_build_2__deps_2catch2-src_2docs_2own-main.html#autotoc_md259',1,'']]],
  ['and_20destructors_36',['Constructors and destructors',['../md_build_2__deps_2catch2-src_2docs_2benchmarks.html#autotoc_md20',1,'']]],
  ['and_20exceptions_20related_20function_37',['Naked exceptions and exceptions-related function',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md131',1,'']]],
  ['and_20failing_20test_20cases_38',['Passing and failing test cases',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md592',1,'']]],
  ['and_20failing_20tests_20at_20runtime_39',['Explicitly skipping, passing, and failing tests at runtime',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md588',1,'']]],
  ['and_20generators_40',['Interaction with Sections and Generators',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md590',1,'']]],
  ['and_20incoming_20changes_41',['Deprecations and incoming changes',['../md_build_2__deps_2catch2-src_2docs_2deprecations.html#autotoc_md140',1,'']]],
  ['and_20lifetimes_42',['Combining operators and lifetimes',['../md_build_2__deps_2catch2-src_2docs_2matchers.html#autotoc_md190',1,'']]],
  ['and_20lldb_20scripts_43',['gdb and lldb scripts',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md34',1,'']]],
  ['and_20minor_20changes_44',['and minor changes',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md514',1,'Improvements and minor changes'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md518',1,'Improvements and minor changes'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md524',1,'Improvements and minor changes'],['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md529',1,'Improvements and minor changes']]],
  ['and_20minor_20improvements_45',['Fixes and minor improvements',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md540',1,'']]],
  ['and_20misc_46',['ci-and-misc',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html',1,'']]],
  ['and_20multiple_20threads_47',['Fatal errors and multiple threads',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md624',1,'']]],
  ['and_20other_20tips_20on_20using_20catch2_48',['Best practices and other tips on using Catch2',['../md_build_2__deps_2catch2-src_2docs_2usage-tips.html#autotoc_md644',1,'']]],
  ['and_20push_20update_20to_20github_49',['Commit and push update to GitHub',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md564',1,'']]],
  ['and_20section_50',['Combining &lt;span class=&quot;tt&quot;&gt;GENERATE&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;SECTION&lt;/span&gt;.',['../md_build_2__deps_2catch2-src_2docs_2generators.html#autotoc_md160',1,'']]],
  ['and_20sections_51',['and sections',['../md_build_2__deps_2catch2-src_2docs_2test-cases-and-sections.html#autotoc_md594',1,'Test cases and sections'],['../md_build_2__deps_2catch2-src_2docs_2tutorial.html#autotoc_md639',1,'Test cases and sections'],['../md_build_2__deps_2catch2-src_2docs_2test-cases-and-sections.html',1,'test-cases-and-sections']]],
  ['and_20so_20on_52',['Tooling integration (CI, test runners and so on)',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md22',1,'']]],
  ['and_20spawned_20threads_53',['and spawned threads',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md615',1,'Assertion-like message macros and spawned threads'],['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md616',1,'Message macros and spawned threads']]],
  ['and_20static_5fcheck_54',['&lt;span class=&quot;tt&quot;&gt;STATIC_REQUIRE&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;STATIC_CHECK&lt;/span&gt;',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md623',1,'']]],
  ['and_20std_3a_3aforward_55',['Avoid &lt;span class=&quot;tt&quot;&gt;std::move&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;std::forward&lt;/span&gt;',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md132',1,'']]],
  ['and_20type_20driven_20tests_56',['Data and Type driven tests',['../md_build_2__deps_2catch2-src_2docs_2tutorial.html#autotoc_md641',1,'']]],
  ['and_20version_20according_20to_20the_20libidentify_20standard_57',['Identify framework and version according to the libIdentify standard',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md73',1,'']]],
  ['another_20c_20test_20framework_58',['Why do we need yet another C++ test framework?',['../md_build_2__deps_2catch2-src_2docs_2why-catch.html#autotoc_md649',1,'']]],
  ['anything_20protocol_20reporter_59',['TAP (Test Anything Protocol) Reporter',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md28',1,'']]],
  ['api_20stability_20policy_60',['What is Catch2&apos;s API stability policy?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md153',1,'']]],
  ['app_20mesh_61',['&lt;a href=&quot;https://github.com/laoshanxi/app-mesh&quot;&gt;App Mesh&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md243',1,'']]],
  ['applications_20tools_62',['Applications &amp;amp; Tools',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md242',1,'']]],
  ['approvaltests_20cpp_63',['&lt;a href=&quot;https://github.com/approvals/ApprovalTests.cpp&quot;&gt;ApprovalTests.cpp&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md210',1,'']]],
  ['approx_64',['&lt;span class=&quot;tt&quot;&gt;Approx&lt;/span&gt;',['../md_build_2__deps_2catch2-src_2docs_2comparing-floating-point-numbers.html#autotoc_md97',1,'']]],
  ['approx_20details_65',['Approx details',['../md_build_2__deps_2catch2-src_2docs_2comparing-floating-point-numbers.html#autotoc_md98',1,'']]],
  ['aprašymas_66',['Aprašymas',['../md__r_e_a_d_m_e.html#autotoc_md666',1,'']]],
  ['arangodb_67',['&lt;a href=&quot;https://github.com/arangodb/arangodb&quot;&gt;ArangoDB&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md244',1,'']]],
  ['are_20run_68',['Specify the order test cases are run',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md68',1,'']]],
  ['args_69',['&lt;a href=&quot;https://github.com/Taywee/args&quot;&gt;args&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md211',1,'']]],
  ['args_20and_20config_70',['Let Catch2 take full control of args and config',['../md_build_2__deps_2catch2-src_2docs_2own-main.html#autotoc_md259',1,'']]],
  ['as_20tags_71',['Filenames as tags',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md83',1,'']]],
  ['asked_20questions_20faq_72',['Frequently Asked Questions (FAQ)',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md148',1,'']]],
  ['assert_20fails_20to_20compile_73',['Visual Studio 2017 &amp;ndash; raw string literal in assert fails to compile',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md176',1,'']]],
  ['assertion_20events_74',['&lt;span class=&quot;tt&quot;&gt;assertion&lt;/span&gt; events',['../md_build_2__deps_2catch2-src_2docs_2reporter-events.html#autotoc_md574',1,'']]],
  ['assertion_20like_20message_20macros_20and_20spawned_20threads_75',['Assertion-like message macros and spawned threads',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md615',1,'']]],
  ['assertion_20macros_76',['Assertion Macros',['../md_build_2__deps_2catch2-src_2docs_2assertions.html#autotoc_md7',1,'']]],
  ['assertion_20macros_20from_20spawned_20threads_77',['Using assertion macros from spawned threads',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md614',1,'']]],
  ['assertion_20related_20macros_78',['Assertion related macros',['../md_build_2__deps_2catch2-src_2docs_2other-macros.html#autotoc_md256',1,'']]],
  ['assertion_20with_20the_20spaceship_20operator_79',['Visual Studio 2022 &amp;ndash; can&apos;t compile assertion with the spaceship operator',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md178',1,'']]],
  ['assertions_80',['assertions',['../md_build_2__deps_2catch2-src_2docs_2assertions.html',1,'']]],
  ['assertions_20expected_20to_20throw_81',['Eliding assertions expected to throw',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md63',1,'']]],
  ['at_20runtime_82',['Skipping Test Cases at Runtime',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md589',1,'']]],
  ['at_20runtime_83',['Explicitly skipping, passing, and failing tests at runtime',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md588',1,'']]],
  ['attribution_84',['Attribution',['../md_build_2__deps_2catch2-src_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md6',1,'']]],
  ['authoring_20benchmarks_85',['Authoring benchmarks',['../md_build_2__deps_2catch2-src_2docs_2benchmarks.html#autotoc_md16',1,'']]],
  ['automake_20reporter_86',['Automake Reporter',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md27',1,'']]],
  ['automatic_20test_20registration_87',['Automatic test registration',['../md_build_2__deps_2catch2-src_2docs_2cmake-integration.html#autotoc_md39',1,'']]],
  ['available_88',['Already available',['../md_build_2__deps_2catch2-src_2docs_2list-of-examples.html#autotoc_md180',1,'']]],
  ['available_20tests_20tags_20or_20reporters_89',['Listing available tests, tags or reporters',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md60',1,'']]],
  ['avoid_20std_3a_3amove_20and_20std_3a_3aforward_90',['Avoid &lt;span class=&quot;tt&quot;&gt;std::move&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;std::forward&lt;/span&gt;',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md132',1,'']]],
  ['azmq_91',['&lt;a href=&quot;https://github.com/zeromq/azmq&quot;&gt;Azmq&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md212',1,'']]]
];
