var searchData=
[
  ['s_20abi_20stability_20policy_0',['What is Catch2&apos;s ABI stability policy?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md152',1,'']]],
  ['s_20api_20stability_20policy_1',['What is Catch2&apos;s API stability policy?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md153',1,'']]],
  ['s_20debug_20break_20b_2',['Overriding Catch&apos;s debug break (&lt;span class=&quot;tt&quot;&gt;-b&lt;/span&gt;)',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md117',1,'']]],
  ['s_20stdlib_3',['Unqualified usage of functions from C&apos;s stdlib',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md133',1,'']]],
  ['safety_4',['Thread Safety',['../md_build_2__deps_2catch2-src_2docs_2assertions.html#autotoc_md13',1,'']]],
  ['safety_5',['safety',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md119',1,'Experimental thread safety'],['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html',1,'thread-safety']]],
  ['safety_20in_20catch2_6',['Thread safety in Catch2',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md613',1,'']]],
  ['samples_7',['Disable statistical analysis of collected benchmark samples',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md79',1,'']]],
  ['samples_20to_20collect_8',['Specify the number of benchmark samples to collect',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md76',1,'']]],
  ['scope_9',['Scope',['../md_build_2__deps_2catch2-src_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md4',1,'']]],
  ['scope_10',['Logging without local scope',['../md_build_2__deps_2catch2-src_2docs_2logging.html#autotoc_md184',1,'']]],
  ['scripts_11',['gdb and lldb scripts',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md34',1,'']]],
  ['seams_12',['&lt;a href=&quot;https://github.com/d-SEAMS/seams-core&quot;&gt;d-SEAMS&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md246',1,'']]],
  ['section_13',['Combining &lt;span class=&quot;tt&quot;&gt;GENERATE&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;SECTION&lt;/span&gt;.',['../md_build_2__deps_2catch2-src_2docs_2generators.html#autotoc_md160',1,'']]],
  ['section_20events_14',['&lt;span class=&quot;tt&quot;&gt;section&lt;/span&gt; events',['../md_build_2__deps_2catch2-src_2docs_2reporter-events.html#autotoc_md573',1,'']]],
  ['section_20fails_15',['Tests might be run again if last section fails',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md170',1,'']]],
  ['section_20to_20run_16',['Specify the section to run',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md82',1,'']]],
  ['sections_17',['sections',['../md_build_2__deps_2catch2-src_2docs_2test-cases-and-sections.html#autotoc_md594',1,'Test cases and sections'],['../md_build_2__deps_2catch2-src_2docs_2tutorial.html#autotoc_md639',1,'Test cases and sections'],['../md_build_2__deps_2catch2-src_2docs_2test-cases-and-sections.html',1,'test-cases-and-sections']]],
  ['sections_20after_20an_20exception_18',['Clang/G++ &amp;ndash; skipping leaf sections after an exception',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md177',1,'']]],
  ['sections_20and_20generators_19',['Interaction with Sections and Generators',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md590',1,'']]],
  ['sections_20nested_20in_20loops_20',['Sections nested in loops',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md169',1,'']]],
  ['security_20policy_21',['Security Policy',['../md_build_2__deps_2catch2-src_2_s_e_c_u_r_i_t_y.html',1,'']]],
  ['seed_20for_20the_20random_20number_20generator_22',['Specify a seed for the Random Number Generator',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md72',1,'']]],
  ['sending_20output_20to_20a_20file_23',['Sending output to a file',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md61',1,'']]],
  ['setup_20teardown_20only_20if_20tests_20will_20be_20run_24',['How do I run global setup/teardown only if tests will be run?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md149',1,'']]],
  ['sfml_25',['&lt;a href=&quot;https://github.com/SFML/SFML&quot;&gt;SFML&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md234',1,'']]],
  ['sharding_26',['Test Sharding',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md85',1,'']]],
  ['showing_20results_20for_20successful_20tests_27',['Showing results for successful tests',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md58',1,'']]],
  ['signature_28',['Signature',['../md_build_2__deps_2catch2-src_2docs_2test-cases-and-sections.html#autotoc_md601',1,'']]],
  ['signature_20based_20parameterised_20test_20fixtures_29',['Signature-based parameterised test fixtures',['../md_build_2__deps_2catch2-src_2docs_2test-fixtures.html#autotoc_md610',1,'']]],
  ['signature_20based_20parametrised_20test_20cases_30',['Signature based parametrised test cases',['../md_build_2__deps_2catch2-src_2docs_2test-cases-and-sections.html#autotoc_md600',1,'']]],
  ['signing_20a_20tag_31',['Signing a tag',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md566',1,'']]],
  ['signing_20the_20amalgamated_20files_32',['Signing the amalgamated files',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md567',1,'']]],
  ['silent_20early_20termination_33',['Create file to guard against silent early termination',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md88',1,'']]],
  ['sistemos_20parametrai_34',['Sistemos parametrai',['../md__r_e_a_d_m_e.html#autotoc_md673',1,'']]],
  ['skip_20all_20benchmarks_35',['Skip all benchmarks',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md75',1,'']]],
  ['skip_20from_20spawned_20threads_36',['FAIL/SKIP from spawned threads',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md622',1,'']]],
  ['skip_20from_20the_20main_20thread_37',['FAIL/SKIP from the main thread',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md621',1,'']]],
  ['skip_20inside_20generators_38',['&lt;span class=&quot;tt&quot;&gt;SKIP&lt;/span&gt; inside generators',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md591',1,'']]],
  ['skipping_20leaf_20sections_20after_20an_20exception_39',['Clang/G++ &amp;ndash; skipping leaf sections after an exception',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md177',1,'']]],
  ['skipping_20passing_20and_20failing_20tests_20at_20runtime_40',['Explicitly skipping, passing, and failing tests at runtime',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md588',1,'']]],
  ['skipping_20passing_20failing_41',['skipping-passing-failing',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html',1,'']]],
  ['skipping_20test_20cases_20at_20runtime_42',['Skipping Test Cases at Runtime',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md589',1,'']]],
  ['slow_43',['MinGW/CygWin compilation (linking) is extremely slow',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md171',1,'']]],
  ['so_20on_44',['Tooling integration (CI, test runners and so on)',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md22',1,'']]],
  ['soci_45',['&lt;a href=&quot;https://github.com/SOCI/soci&quot;&gt;SOCI&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md235',1,'']]],
  ['sonarqube_20reporter_46',['SonarQube Reporter',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md29',1,'']]],
  ['source_20file_20template_47',['New source file template',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md135',1,'']]],
  ['source_20projects_20using_20catch2_48',['Open Source projects using Catch2',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md206',1,'']]],
  ['spaceship_20operator_49',['Visual Studio 2022 &amp;ndash; can&apos;t compile assertion with the spaceship operator',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md178',1,'']]],
  ['spawned_20threads_50',['spawned threads',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md619',1,'&lt;span class=&quot;tt&quot;&gt;REQUIRE&lt;/span&gt; from spawned threads'],['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md618',1,'&lt;span class=&quot;tt&quot;&gt;REQUIRE&lt;/span&gt; from the main thread, &lt;span class=&quot;tt&quot;&gt;CHECK&lt;/span&gt; from spawned threads'],['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md615',1,'Assertion-like message macros and spawned threads'],['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md622',1,'FAIL/SKIP from spawned threads'],['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md616',1,'Message macros and spawned threads'],['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md614',1,'Using assertion macros from spawned threads']]],
  ['special_20tags_51',['Special Tags',['../md_build_2__deps_2catch2-src_2docs_2test-cases-and-sections.html#autotoc_md596',1,'']]],
  ['specialisation_52',['specialisation',['../md_build_2__deps_2catch2-src_2docs_2tostring.html#autotoc_md630',1,'Catch::is_range specialisation'],['../md_build_2__deps_2catch2-src_2docs_2tostring.html#autotoc_md629',1,'Catch::StringMaker specialisation']]],
  ['specification_53',['Benchmark specification',['../md_build_2__deps_2catch2-src_2docs_2benchmarks.html#autotoc_md18',1,'']]],
  ['specified_20in_20template_20type_20lists_54',['Template fixtures with types specified in template type lists',['../md_build_2__deps_2catch2-src_2docs_2test-fixtures.html#autotoc_md611',1,'']]],
  ['specify_20a_20seed_20for_20the_20random_20number_20generator_55',['Specify a seed for the Random Number Generator',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md72',1,'']]],
  ['specify_20the_20amount_20of_20time_20in_20milliseconds_20spent_20on_20warming_20up_20each_20test_56',['Specify the amount of time in milliseconds spent on warming up each test',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md80',1,'']]],
  ['specify_20the_20confidence_20interval_20for_20bootstrapping_57',['Specify the confidence-interval for bootstrapping',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md78',1,'']]],
  ['specify_20the_20number_20of_20benchmark_20samples_20to_20collect_58',['Specify the number of benchmark samples to collect',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md76',1,'']]],
  ['specify_20the_20number_20of_20resamples_20for_20bootstrapping_59',['Specify the number of resamples for bootstrapping',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md77',1,'']]],
  ['specify_20the_20order_20test_20cases_20are_20run_60',['Specify the order test cases are run',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md68',1,'']]],
  ['specify_20the_20section_20to_20run_61',['Specify the section to run',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md82',1,'']]],
  ['specifying_20which_20tests_20to_20run_62',['Specifying which tests to run',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md54',1,'']]],
  ['spectre_63',['&lt;a href=&quot;https://github.com/sxs-collaboration/spectre&quot;&gt;SpECTRE&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md252',1,'']]],
  ['spent_20on_20warming_20up_20each_20test_64',['Specify the amount of time in milliseconds spent on warming up each test',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md80',1,'']]],
  ['stability_20policy_65',['stability policy',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md152',1,'What is Catch2&apos;s ABI stability policy?'],['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md153',1,'What is Catch2&apos;s API stability policy?']]],
  ['standard_66',['Identify framework and version according to the libIdentify standard',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md73',1,'']]],
  ['standard_20version_67',['C++ standard version',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md128',1,'']]],
  ['standardese_68',['&lt;a href=&quot;https://github.com/foonathan/standardese&quot;&gt;Standardese&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md253',1,'']]],
  ['standards_69',['Our Standards',['../md_build_2__deps_2catch2-src_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md2',1,'']]],
  ['state_20between_20running_20different_20tests_70',['How do I clean up global state between running different tests?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md150',1,'']]],
  ['static_20analysis_20support_71',['Static analysis support',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md118',1,'']]],
  ['static_5fcheck_72',['&lt;span class=&quot;tt&quot;&gt;STATIC_REQUIRE&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;STATIC_CHECK&lt;/span&gt;',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md623',1,'']]],
  ['static_5frequire_20and_20static_5fcheck_73',['&lt;span class=&quot;tt&quot;&gt;STATIC_REQUIRE&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;STATIC_CHECK&lt;/span&gt;',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md623',1,'']]],
  ['statistical_20analysis_20of_20collected_20benchmark_20samples_74',['Disable statistical analysis of collected benchmark samples',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md79',1,'']]],
  ['std_3a_3aforward_75',['Avoid &lt;span class=&quot;tt&quot;&gt;std::move&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;std::forward&lt;/span&gt;',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md132',1,'']]],
  ['std_3a_3amove_20and_20std_3a_3aforward_76',['Avoid &lt;span class=&quot;tt&quot;&gt;std::move&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;std::forward&lt;/span&gt;',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md132',1,'']]],
  ['std_3a_3aostream_77',['operator &amp;lt;&amp;lt; overload for std::ostream',['../md_build_2__deps_2catch2-src_2docs_2tostring.html#autotoc_md628',1,'']]],
  ['std_3a_3astring_20matchers_78',['&lt;span class=&quot;tt&quot;&gt;std::string&lt;/span&gt; matchers',['../md_build_2__deps_2catch2-src_2docs_2matchers.html#autotoc_md192',1,'']]],
  ['stdlib_79',['Unqualified usage of functions from C&apos;s stdlib',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md133',1,'']]],
  ['stdout_80',['stdout',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md104',1,'']]],
  ['steps_81',['steps',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md560',1,'Necessary steps'],['../md_build_2__deps_2catch2-src_2docs_2tutorial.html#autotoc_md642',1,'Next steps']]],
  ['streaming_20macros_82',['Streaming macros',['../md_build_2__deps_2catch2-src_2docs_2logging.html#autotoc_md185',1,'']]],
  ['string_20conversions_83',['String conversions',['../md_build_2__deps_2catch2-src_2docs_2tostring.html#autotoc_md627',1,'']]],
  ['string_20literal_20in_20assert_20fails_20to_20compile_84',['Visual Studio 2017 &amp;ndash; raw string literal in assert fails to compile',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md176',1,'']]],
  ['stringification_85',['Enabling stringification',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md114',1,'']]],
  ['stringifier_86',['Fallback stringifier',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md105',1,'']]],
  ['struktūros_20palyginimas_87',['Klasių struktūros palyginimas',['../md__r_e_a_d_m_e.html#autotoc_md697',1,'']]],
  ['studio_202017_20ndash_20raw_20string_20literal_20in_20assert_20fails_20to_20compile_88',['Visual Studio 2017 &amp;ndash; raw string literal in assert fails to compile',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md176',1,'']]],
  ['studio_202022_20ndash_20can_20t_20compile_20assertion_20with_20the_20spaceship_20operator_89',['Visual Studio 2022 &amp;ndash; can&apos;t compile assertion with the spaceship operator',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md178',1,'']]],
  ['style_90',['style',['../md_build_2__deps_2catch2-src_2docs_2matchers.html#autotoc_md199',1,'Writing custom matchers (new style)'],['../md_build_2__deps_2catch2-src_2docs_2matchers.html#autotoc_md198',1,'Writing custom matchers (old style)']]],
  ['style_20test_20cases_91',['BDD-style test cases',['../md_build_2__deps_2catch2-src_2docs_2test-cases-and-sections.html#autotoc_md598',1,'']]],
  ['style_20testing_92',['BDD style testing',['../md_build_2__deps_2catch2-src_2docs_2tutorial.html#autotoc_md640',1,'']]],
  ['successful_20tests_93',['Showing results for successful tests',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md58',1,'']]],
  ['supplying_20main_20yourself_94',['Supplying main() yourself',['../md_build_2__deps_2catch2-src_2docs_2own-main.html#autotoc_md258',1,'']]],
  ['support_95',['support',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md107',1,'Bazel support'],['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md118',1,'Static analysis support']]],
  ['support_20running_20tests_20in_20parallel_96',['Does Catch2 support running tests in parallel?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md154',1,'']]],
  ['supported_20versions_97',['Supported Versions',['../md_build_2__deps_2catch2-src_2_s_e_c_u_r_i_t_y.html#autotoc_md663',1,'']]],
  ['systems_98',['Continuous Integration systems',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md23',1,'']]]
];
