var searchData=
[
  ['rand_0',['rand',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md71',1,'']]],
  ['random_20number_20generator_1',['Specify a seed for the Random Number Generator',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md72',1,'']]],
  ['random_20number_20generators_3a_20details_2',['Random number generators: details',['../md_build_2__deps_2catch2-src_2docs_2generators.html#autotoc_md162',1,'']]],
  ['range_20matchers_3',['Generic range Matchers',['../md_build_2__deps_2catch2-src_2docs_2matchers.html#autotoc_md197',1,'']]],
  ['raspigcd_4',['&lt;a href=&quot;https://github.com/pantadeusz/raspigcd&quot;&gt;raspigcd&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md251',1,'']]],
  ['raw_20string_20literal_20in_20assert_20fails_20to_20compile_5',['Visual Studio 2017 &amp;ndash; raw string literal in assert fails to compile',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md176',1,'']]],
  ['reactive_20extensions_20rxcpp_6',['&lt;a href=&quot;https://github.com/Reactive-Extensions/RxCpp&quot;&gt;Reactive-Extensions/ RxCpp&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md233',1,'']]],
  ['reference_7',['Reference',['../dir_ca2eebc99d764991008be71d0d36fef8.html#autotoc_md264',1,'']]],
  ['registration_8',['Automatic test registration',['../md_build_2__deps_2catch2-src_2docs_2cmake-integration.html#autotoc_md39',1,'']]],
  ['related_20function_9',['Naked exceptions and exceptions-related function',['../md_build_2__deps_2catch2-src_2docs_2contributing.html#autotoc_md131',1,'']]],
  ['related_20macros_10',['related macros',['../md_build_2__deps_2catch2-src_2docs_2other-macros.html#autotoc_md256',1,'Assertion related macros'],['../md_build_2__deps_2catch2-src_2docs_2other-macros.html#autotoc_md257',1,'Test case related macros']]],
  ['releasai_11',['Releasai',['../md__r_e_a_d_m_e.html#autotoc_md667',1,'Releasai'],['../md__r_e_a_d_m_e.html#autotoc_md682',1,'Releasai']]],
  ['release_12',['How to release',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md559',1,'']]],
  ['release_20notes_13',['Release notes',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md265',1,'Release notes'],['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md563',1,'Release notes']]],
  ['release_20notes_14',['release-notes',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html',1,'']]],
  ['release_20on_20github_15',['Release on GitHub',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md565',1,'']]],
  ['release_20process_16',['release-process',['../md_build_2__deps_2catch2-src_2docs_2release-process.html',1,'']]],
  ['released_17',['Catch2 v3 has been released!',['../dir_22a2b4a55221191fac099ecd648bab0b.html#autotoc_md659',1,'']]],
  ['repeatability_20guarantees_20does_20catch2_20provide_18',['What repeatability guarantees does Catch2 provide?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md156',1,'']]],
  ['reporter_19',['Reporter',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md27',1,'Automake Reporter'],['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md25',1,'JUnit Reporter'],['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md29',1,'SonarQube Reporter'],['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md28',1,'TAP (Test Anything Protocol) Reporter'],['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md26',1,'TeamCity Reporter'],['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md24',1,'XML Reporter']]],
  ['reporter_20',['reporter',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md106',1,'Default reporter'],['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md586',1,'Other expected functionality of a reporter'],['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md582',1,'Writing your own reporter']]],
  ['reporter_20bases_21',['Utility reporter bases',['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md583',1,'']]],
  ['reporter_20configuration_22',['Per-reporter configuration',['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md585',1,'']]],
  ['reporter_20events_23',['Reporter events',['../md_build_2__deps_2catch2-src_2docs_2reporter-events.html#autotoc_md568',1,'']]],
  ['reporter_20events_24',['reporter-events',['../md_build_2__deps_2catch2-src_2docs_2reporter-events.html',1,'']]],
  ['reporter_20to_20use_25',['Choosing a reporter to use',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md56',1,'']]],
  ['reporterpreferences_26',['&lt;span class=&quot;tt&quot;&gt;ReporterPreferences&lt;/span&gt;',['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md584',1,'']]],
  ['reporters_27',['Reporters',['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md579',1,'']]],
  ['reporters_28',['reporters',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md60',1,'Listing available tests, tags or reporters'],['../md_build_2__deps_2catch2-src_2docs_2reporters.html',1,'reporters'],['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md580',1,'Using different reporters'],['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md581',1,'Using multiple reporters'],['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md151',1,'Why cannot I derive from the built-in reporters?']]],
  ['reporting_20a_20vulnerability_29',['Reporting a Vulnerability',['../md_build_2__deps_2catch2-src_2_s_e_c_u_r_i_t_y.html#autotoc_md664',1,'']]],
  ['reporting_20timings_30',['Reporting timings',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md66',1,'']]],
  ['repository_31',['Installing Catch2 from git repository',['../md_build_2__deps_2catch2-src_2docs_2cmake-integration.html#autotoc_md49',1,'']]],
  ['reproducibility_32',['Reproducibility',['../md_build_2__deps_2catch2-src_2docs_2generators.html#autotoc_md163',1,'']]],
  ['require_20from_20spawned_20threads_33',['&lt;span class=&quot;tt&quot;&gt;REQUIRE&lt;/span&gt; from spawned threads',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md619',1,'']]],
  ['require_20from_20the_20main_20thread_20check_20from_20spawned_20threads_34',['&lt;span class=&quot;tt&quot;&gt;REQUIRE&lt;/span&gt; from the main thread, &lt;span class=&quot;tt&quot;&gt;CHECK&lt;/span&gt; from spawned threads',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md618',1,'']]],
  ['resamples_20for_20bootstrapping_35',['Specify the number of resamples for bootstrapping',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md77',1,'']]],
  ['responsibilities_36',['Our Responsibilities',['../md_build_2__deps_2catch2-src_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md3',1,'']]],
  ['results_20for_20successful_20tests_37',['Showing results for successful tests',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md58',1,'']]],
  ['retired_38',['Retired',['../md_build_2__deps_2catch2-src_2_m_a_i_n_t_a_i_n_e_r_s.html#autotoc_md657',1,'']]],
  ['rule_20of_20three_20implementacija_39',['Rule of Three Implementacija',['../md__r_e_a_d_m_e.html#autotoc_md689',1,'']]],
  ['run_40',['run',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md149',1,'How do I run global setup/teardown only if tests will be run?'],['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md62',1,'Naming a test run'],['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md68',1,'Specify the order test cases are run'],['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md82',1,'Specify the section to run'],['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md54',1,'Specifying which tests to run']]],
  ['run_20again_20if_20last_20section_20fails_41',['Tests might be run again if last section fails',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md170',1,'']]],
  ['run_20from_20a_20file_42',['Load test names to run from a file',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md67',1,'']]],
  ['run_20global_20setup_20teardown_20only_20if_20tests_20will_20be_20run_43',['How do I run global setup/teardown only if tests will be run?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md149',1,'']]],
  ['runner_20integration_44',['Bazel test runner integration',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md30',1,'']]],
  ['runners_20and_20so_20on_45',['Tooling integration (CI, test runners and so on)',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md22',1,'']]],
  ['running_20different_20tests_46',['How do I clean up global state between running different tests?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md150',1,'']]],
  ['running_20events_47',['Test running events',['../md_build_2__deps_2catch2-src_2docs_2reporter-events.html#autotoc_md569',1,'']]],
  ['running_20multiple_20tests_20in_20parallel_48',['Running multiple tests in parallel',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md174',1,'']]],
  ['running_20tests_49',['Running tests',['../md_build_2__deps_2catch2-src_2docs_2usage-tips.html#autotoc_md645',1,'']]],
  ['running_20tests_20in_20parallel_50',['Running tests in parallel',['../md_build_2__deps_2catch2-src_2docs_2usage-tips.html#autotoc_md646',1,'']]],
  ['running_20tests_20in_20parallel_51',['Does Catch2 support running tests in parallel?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md154',1,'']]],
  ['running_20the_20binary_20without_20tests_52',['Allow running the binary without tests',['../md_build_2__deps_2catch2-src_2docs_2command-line.html#autotoc_md86',1,'']]],
  ['runtime_53',['Runtime',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md223',1,'&lt;a href=&quot;https://github.com/ROCm-Developer-Tools/HIP-CPU&quot;&gt;HIP CPU Runtime&lt;/a&gt;'],['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md589',1,'Skipping Test Cases at Runtime']]],
  ['runtime_54',['Explicitly skipping, passing, and failing tests at runtime',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md588',1,'']]],
  ['rxcpp_55',['&lt;a href=&quot;https://github.com/Reactive-Extensions/RxCpp&quot;&gt;Reactive-Extensions/ RxCpp&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md233',1,'']]]
];
