var searchData=
[
  ['palyginimas_0',['Klasių struktūros palyginimas',['../md__r_e_a_d_m_e.html#autotoc_md697',1,'']]],
  ['parallel_1',['parallel',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md154',1,'Does Catch2 support running tests in parallel?'],['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md174',1,'Running multiple tests in parallel'],['../md_build_2__deps_2catch2-src_2docs_2usage-tips.html#autotoc_md646',1,'Running tests in parallel']]],
  ['parameterised_20test_20fixtures_2',['Signature-based parameterised test fixtures',['../md_build_2__deps_2catch2-src_2docs_2test-fixtures.html#autotoc_md610',1,'']]],
  ['parametrai_3',['Sistemos parametrai',['../md__r_e_a_d_m_e.html#autotoc_md673',1,'']]],
  ['parametrised_20test_20cases_4',['parametrised test cases',['../md_build_2__deps_2catch2-src_2docs_2test-cases-and-sections.html#autotoc_md600',1,'Signature based parametrised test cases'],['../md_build_2__deps_2catch2-src_2docs_2test-cases-and-sections.html#autotoc_md599',1,'Type parametrised test cases']]],
  ['parseandaddcatchtests_20cmake_5',['ParseAndAddCatchTests cmake',['../md_build_2__deps_2catch2-src_2docs_2cmake-integration.html#autotoc_md43',1,'&lt;span class=&quot;tt&quot;&gt;ParseAndAddCatchTests.cmake&lt;/span&gt;'],['../md_build_2__deps_2catch2-src_2docs_2deprecations.html#autotoc_md141',1,'&lt;span class=&quot;tt&quot;&gt;ParseAndAddCatchTests.cmake&lt;/span&gt;']]],
  ['party_20bugs_6',['3rd party bugs',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md175',1,'']]],
  ['passing_20and_20failing_20test_20cases_7',['Passing and failing test cases',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md592',1,'']]],
  ['passing_20and_20failing_20tests_20at_20runtime_8',['Explicitly skipping, passing, and failing tests at runtime',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html#autotoc_md588',1,'']]],
  ['passing_20failing_9',['skipping-passing-failing',['../md_build_2__deps_2catch2-src_2docs_2skipping-passing-failing.html',1,'']]],
  ['per_20reporter_20configuration_10',['Per-reporter configuration',['../md_build_2__deps_2catch2-src_2docs_2reporters.html#autotoc_md585',1,'']]],
  ['performance_20overhead_11',['Performance overhead',['../md_build_2__deps_2catch2-src_2docs_2thread-safety.html#autotoc_md625',1,'']]],
  ['pkg_20config_12',['pkg-config',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md33',1,'']]],
  ['planned_13',['Planned',['../md_build_2__deps_2catch2-src_2docs_2list-of-examples.html#autotoc_md181',1,'']]],
  ['pledge_14',['Our Pledge',['../md_build_2__deps_2catch2-src_2_c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md1',1,'']]],
  ['point_20comparisons_15',['Floating point comparisons',['../md_build_2__deps_2catch2-src_2docs_2assertions.html#autotoc_md10',1,'']]],
  ['point_20matchers_16',['point matchers',['../md_build_2__deps_2catch2-src_2docs_2comparing-floating-point-numbers.html#autotoc_md93',1,'Floating point matchers'],['../md_build_2__deps_2catch2-src_2docs_2matchers.html#autotoc_md194',1,'Floating point matchers']]],
  ['point_20numbers_17',['comparing-floating-point-numbers',['../md_build_2__deps_2catch2-src_2docs_2comparing-floating-point-numbers.html',1,'']]],
  ['point_20numbers_20with_20catch2_18',['Comparing floating point numbers with Catch2',['../md_build_2__deps_2catch2-src_2docs_2comparing-floating-point-numbers.html#autotoc_md92',1,'']]],
  ['point_20precision_19',['Floating point precision',['../md_build_2__deps_2catch2-src_2docs_2tostring.html#autotoc_md633',1,'']]],
  ['policy_20',['Security Policy',['../md_build_2__deps_2catch2-src_2_s_e_c_u_r_i_t_y.html',1,'']]],
  ['policy_21',['policy',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md152',1,'What is Catch2&apos;s ABI stability policy?'],['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md153',1,'What is Catch2&apos;s API stability policy?']]],
  ['polymorphic_5fvalue_22',['&lt;a href=&quot;https://github.com/jbcoe/polymorphic_value&quot;&gt;polymorphic_value&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md231',1,'']]],
  ['pophead_23',['&lt;a href=&quot;https://github.com/SPC-Some-Polish-Coders/PopHead&quot;&gt;PopHead&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md250',1,'']]],
  ['porting_24',['Things that can break during porting',['../md_build_2__deps_2catch2-src_2docs_2migrate-v2-to-v3.html#autotoc_md204',1,'']]],
  ['potentially_20breaking_20changes_25',['(Potentially) Breaking changes',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md343',1,'']]],
  ['ppconsul_26',['&lt;a href=&quot;https://github.com/oliora/ppconsul&quot;&gt;Ppconsul&lt;/a&gt;',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md232',1,'']]],
  ['practices_20and_20other_20tips_20on_20using_20catch2_27',['Best practices and other tips on using Catch2',['../md_build_2__deps_2catch2-src_2docs_2usage-tips.html#autotoc_md644',1,'']]],
  ['precision_28',['Floating point precision',['../md_build_2__deps_2catch2-src_2docs_2tostring.html#autotoc_md633',1,'']]],
  ['prefixing_20catch_20macros_29',['Prefixing Catch macros',['../md_build_2__deps_2catch2-src_2docs_2configuration.html#autotoc_md101',1,'']]],
  ['priskyrimo_20operatorius_30',['Kopijavimo Priskyrimo Operatorius',['../md__r_e_a_d_m_e.html#autotoc_md691',1,'']]],
  ['procedure_31',['Execution procedure',['../md_build_2__deps_2catch2-src_2docs_2benchmarks.html#autotoc_md17',1,'']]],
  ['process_32',['release-process',['../md_build_2__deps_2catch2-src_2docs_2release-process.html',1,'']]],
  ['process_20isolation_20in_20a_20test_33',['Process isolation in a test',['../md_build_2__deps_2catch2-src_2docs_2limitations.html#autotoc_md173',1,'']]],
  ['project_20options_34',['CMake project options',['../md_build_2__deps_2catch2-src_2docs_2cmake-integration.html#autotoc_md47',1,'']]],
  ['projects_20from_20v2_20to_20v3_35',['How to migrate projects from v2 to v3',['../md_build_2__deps_2catch2-src_2docs_2migrate-v2-to-v3.html#autotoc_md202',1,'']]],
  ['projects_20using_20catch2_36',['Open Source projects using Catch2',['../md_build_2__deps_2catch2-src_2docs_2opensource-users.html#autotoc_md206',1,'']]],
  ['projects_3a_37',['Cmake/ projects:',['../md_build_2__deps_2catch2-src_2docs_2release-notes.html#autotoc_md553',1,'']]],
  ['protocol_20reporter_38',['TAP (Test Anything Protocol) Reporter',['../md_build_2__deps_2catch2-src_2docs_2ci-and-misc.html#autotoc_md28',1,'']]],
  ['provide_39',['What repeatability guarantees does Catch2 provide?',['../md_build_2__deps_2catch2-src_2docs_2faq.html#autotoc_md156',1,'']]],
  ['provided_20generators_40',['Provided generators',['../md_build_2__deps_2catch2-src_2docs_2generators.html#autotoc_md161',1,'']]],
  ['push_20update_20to_20github_41',['Commit and push update to GitHub',['../md_build_2__deps_2catch2-src_2docs_2release-process.html#autotoc_md564',1,'']]]
];
